---
title: Bugo
description: Bootstrap + Hugo Static Site Generator
baseURL: "/"
languageCode: en-us
summaryLength: 60
canonifyURLs: true
enableRobotsTXT: true
permalinks:
  posts: "/blog/:slug"
googleAnalytics: ''
blackFriday:
  hrefTargetBlank: true
taxonomies:
  category: categories
  tags: tags
theme:
- bugo-base-theme
metaDataFormat: yaml
frontmatter:
- date:
  - date
  - publishDate
  - lastmod
- lastmod:
  - ":git"
  - lastmod
  - date
  - publishDate
- publishDate:
  - publishDate
  - date
- expiryDate: expiryDate
assetDir: static/assets
publishDir: public
mediaTypes:
  text/vcard:
    suffixes:
    - vcf
outputFormats:
  vcf:
    name: vcf
    baseName: contact-info
    mediaType: text/vcard
    isPlainText: true
outputs:
  home:
  - HTML
  - RSS
  page:
  - HTML
  - vcf
  section:
  - HTML
menu:
  main:
  - url: "#"
    name: Client Portal
    weight: 6
  - url: https://app.tolerisk.com/Investor.aspx?a=82c07446-9e87-45a5-a62b-afb9681c228e
    name: Risk Tolerance
    weight: 5
  mobile:
  - url: "#"
    name: Client Portal
    weight: 7
  - url: https://app.tolerisk.com/Investor.aspx?a=82c07446-9e87-45a5-a62b-afb9681c228e
    name: Risk Tolerance
    weight: 6
