---
title: Bugo.io
description: Boilerplate Boostrap Website for Forestry.io
baseURL: "/"
languageCode: en-us
summaryLength: 60
canonifyURLs: true
enableRobotsTXT: true
googleAnalytics: ''
taxonomies:
  category: categories
  tags: tags
theme:
- bugo-base-theme
- bugo-profiles
- bugo-search
metaDataFormat: yaml
frontmatter:
- date:
  - date
  - publishDate
  - lastmod
- lastmod:
  - ":git"
  - lastmod
  - date
  - publishDate
- publishDate:
  - publishDate
  - date
- expiryDate: expiryDate
assetDir: static/assets
publishDir: public
outputs: 
home:
- HTML
- JSON
- RSS
page:
- HTML
menu:
  footer:
  - url: "/"
    name: Home
    weight: 2
  - url: "/posts/"
    name: Posts
    weight: 1
  copyright:
  - url: "/privacy/"
    name: Privacy
    weight: 1
  - url: "/terms-of-use/"
    name: Terms of Use
    weight: 2
  secondary:
  - url: "#"
    name: Login
    weight: 1
  - url: "#"
    name: Support
    weight: 2
