---
title: Bugo
description: Bugo is a full-featured static site framework. Build low-maintenance,
  secure, high performance websites.
baseURL: "/"
languageCode: en-us
summaryLength: 25
canonifyURLs: true
enableRobotsTXT: true
contentDir: content
permalinks:
  posts: "/blog/:slug"
  team: "/team/:slug"
googleAnalytics: UA-139385403-1
blackFriday:
  hrefTargetBlank: true
taxonomies:
  category: categories
  tags: tags
theme:
- bugo-base-theme
metaDataFormat: yaml
frontmatter:
- date:
  - date
  - publishDate
  - lastmod
- lastmod:
  - ":git"
  - lastmod
  - date
  - publishDate
  date: []
- publishDate:
  - publishDate
  - date
  date: []
- expiryDate: expiryDate
  date: []
assetDir: static/assets
publishDir: public
mediaTypes:
  text/vcard:
    suffixes:
    - vcf
outputFormats:
  vcf:
    name: vcf
    baseName: contact-info
    mediaType: text/vcard
    isPlainText: true
outputs:
  home:
  - HTML
  - RSS
  page:
  - HTML
  - vcf
  section:
  - HTML
enable_robots_txt: true
enable_inline_shortcodes: true
enableEmoji: true
paginate: 10
googleanalytics: ''
enableInlineShortcodes: true
menu:
  main:
  - identifier: docs
    name: Docs
    title: Bugo Documentation
    url: "/docs/"
    weight: 1
    pre: ''
    post: ''
    parent: ''
  secondary: []
  footer: []
  privacy:
  - identifier: sitemap
    title: Sitemap
    name: Sitemap
    url: "/sitemap/"
    weight: 
    pre: ''
    post: ''
google_verification_meta_field: ''
enablerobotstxt: true
