---
title: Bugo
description: Boostrap + Hugo = ❤️
baseURL: "/"
languageCode: en-us
summaryLength: 60
canonifyURLs: true
enableRobotsTXT: true
contentDir: content
permalinks:
  posts: "/blog/:slug"
  team: "/team/:slug"
googleAnalytics: ''
blackFriday:
  hrefTargetBlank: true
taxonomies:
  category: categories
  tags: tags
theme:
- bugo-base-theme
metaDataFormat: yaml
frontmatter:
- date:
  - date
  - publishDate
  - lastmod
- lastmod:
  - ":git"
  - lastmod
  - date
  - publishDate
- publishDate:
  - publishDate
  - date
- expiryDate: expiryDate
assetDir: static/assets
publishDir: public
mediaTypes:
  text/vcard:
    suffixes:
    - vcf
outputFormats:
  vcf:
    name: vcf
    baseName: contact-info
    mediaType: text/vcard
    isPlainText: true
outputs:
  home:
  - HTML
  - RSS
  page:
  - HTML
  - vcf
  section:
  - HTML
enable_robots_txt: true
enable_inline_shortcodes: true
enableemoji: true
paginate: 10
blackfriday: {}
enableEmoji: true
googleanalytics: ''
enableInlineShortcodes: true
# sectionPagesMenu: main
menu:
  main:
  - identifier: docs
    name: Docs
    title: Bugo Documentation
    url: /docs/
    weight: 2
  - identifier: news
    name: News
    title: Bugo News
    url: /posts/
    weight: 1
  secondary:
  - identifier: bootsrap
    name: Bootstrap
    title: Boostrap Framework
    url: https://getbootstrap.com
    weight: -110
  - identifier: hugo
    name: Hugo
    title: Hugo Static Site Generator
    url: https://gohugo.io
    weight: -110
  
