---
title: Bugo.io
description: Boilerplate Boostrap Website for Forestry.io
baseURL: "/"
languageCode: en-us
summaryLength: 60
canonifyURLs: true
enableRobotsTXT: true
googleAnalytics: ''
blackFriday:
  hrefTargetBlank: true
taxonomies:
  category: categories
  tags: tags
theme:
- bugo-base-theme
- bugo-profiles
- bugo-search
metaDataFormat: yaml
frontmatter:
- date:
  - date
  - publishDate
  - lastmod
- lastmod:
  - ":git"
  - lastmod
  - date
  - publishDate
- publishDate:
  - publishDate
  - date
- expiryDate: expiryDate
assetDir: static/assets
publishDir: public
outputs: 
home:
- HTML
- JSON
- RSS
page:
- HTML
menu:
  main:
  - url: "#"
    name: Test 2
    parent: Contact Us
    weight: 2
  - url: https://google.com
    name: Test 1
    parent: Contact Us
    weight: 1
  secondary:
  - url: http://google.com
    name: Client Portal
    weight: 2
