---
title: Bugo.io
description: Boilerplate Boostrap Website for Forestry.io
baseURL: "/"
languageCode: en-us
summaryLength: 60
canonifyURLs: true
enableRobotsTXT: true
googleAnalytics: ''
blackFriday:
  hrefTargetBlank: true
taxonomies:
  category: categories
  tags: tags
theme:
- bugo-base-theme
- bugo-profiles
- bugo-search
metaDataFormat: yaml
frontmatter:
- date:
  - date
  - publishDate
  - lastmod
- lastmod:
  - ":git"
  - lastmod
  - date
  - publishDate
- publishDate:
  - publishDate
  - date
- expiryDate: expiryDate
assetDir: static/assets
publishDir: public
outputs: 
home:
- HTML
- JSON
- RSS
page:
- HTML
menu:
  main:
  - url: https://app.tolerisk.com/Investor.aspx?a=82c07446-9e87-45a5-a62b-afb9681c228e
    name: Risk Tolerance
    weight: 5
