---
title: Bugo
description: Boostrap + Hugo = ❤️
baseURL: "/"
languageCode: en-us
summaryLength: 60
canonifyURLs: true
enableRobotsTXT: true
enableInlineShortcodes: true
enableemoji: true
paginate: 10
contentDir: content_sample
permalinks:
- posts: "/blog/:slug"
- team: "/team/:slug"
googleAnalytics: ''
blackFriday:
  hrefTargetBlank: true
taxonomies:
  category: categories
  tags: tags
theme:
- bugo-base-theme
metaDataFormat: yaml
frontmatter:
- date:
  - date
  - publishDate
  - lastmod
- lastmod:
  - ":git"
  - lastmod
  - date
  - publishDate
- publishDate:
  - publishDate
  - date
- expiryDate: expiryDate
assetDir: static/assets
publishDir: public
mediaTypes:
  text/vcard:
    suffixes:
    - vcf
outputFormats:
  vcf:
    name: vcf
    baseName: contact-info
    mediaType: text/vcard
    isPlainText: true
outputs:
  home:
  - HTML
  - RSS
  page:
  - HTML
  - vcf
  section:
  - HTML
