---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url:
sections:
- type: directory
  path: content
  label: Home Page
  create: all
  match: _index.*
  new_doc_ext: md
  templates:
  - landing-page
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  new_doc_ext: md
  templates:
  - pages
- type: directory
  path: content/blog
  label: Blog Page
  create: all
  match: _index.*
  new_doc_ext: md
  templates:
  - list
- type: directory
  path: content/blog
  label: Posts
  create: all
  match: "**/*"
  exclude: _index.*
  new_doc_ext: md
  templates:
  - posts
- type: directory
  path: content/docs
  label: Docs Landing
  create: all
  match: _index.*
  new_doc_ext: md
  templates:
  - pages
- type: directory
  path: content/docs
  label: Docs
  create: all
  match: "**/*"
  exclude: _index.*
  new_doc_ext: md
  templates:
  - docs
- type: heading
  label: Config
- type: document
  path: data/information.yaml
  label: Site Information
  templates:
  - site-information
- type: document
  path: data/config.yaml
  label: Site Config
upload_dir: ''
public_path: ''
front_matter_path: ''
use_front_matter_path:
file_template: ":filename:"
version: 0.42.1
