---
new_page_extension: md
auto_deploy: true
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*"
  exclude: "{posts/*,profiles/*}"
- type: document
  path: data/config.yaml
  label: Site Options
- type: heading
  label: Documentation
- type: document
  path: content/documentation/markdown-cheatsheet.md
  label: Markdown Cheatsheet
  read_only: true
upload_dir: ''
public_path: https://res.cloudinary.com/dw7ezzuop/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_command: hugo
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  publish_env:
  - HUGO_VERSION=0.53
  preview_output_directory: public
  output_directory: public
version: '0.53'
