---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
  exclude: _index.*
  templates:
  - post-attributes
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*"
  exclude: "{_index.,posts,profiles}/*"
- type: document
  path: data/config.yaml
  label: Site Options
- type: document
  path: data/categories.yaml
  label: Categories
upload_dir: ''
public_path: https://res.cloudinary.com/matthew-antone/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.53
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.53
  preview_output_directory: public
  output_directory: public
version: '0.53'
