---
label: Bugo Config
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: textarea
  name: description
  label: description
- type: text
  name: baseURL
  label: baseURL
- type: number
  name: summaryLength
  label: summaryLength
- type: text
  name: contentDir
  label: contentDir
- type: text
  name: googleAnalytics
  label: googleAnalytics
- type: number
  name: paginate
  label: paginate
- type: field_group
  name: menu
  label: menu
  fields:
  - type: field_group_list
    name: main
    label: main
    fields:
    - type: text
      name: identifier
      label: identifier
    - type: text
      name: name
      label: name
    - type: text
      name: title
      label: title
    - type: text
      name: url
      label: url
    - type: number
      name: weight
      label: weight
    - type: text
      name: pre
      label: pre
- type: boolean
  name: enableEmoji
  label: enableEmoji
- type: boolean
  name: enableInlineShortcodes
  label: enableInlineShortcodes
- type: boolean
  name: enable_robots_txt
  label: enable_robots_txt
- type: list
  name: theme
  label: theme
- type: field_group
  name: mediaTypes
  label: mediaTypes
  fields:
  - type: field_group
    name: text/vcard
    label: text/vcard
    fields:
    - type: list
      name: suffixes
      label: suffixes
- type: field_group
  name: outputFormats
  label: outputFormats
  fields:
  - type: field_group
    name: vcf
    label: vcf
    fields:
    - type: text
      name: name
      label: name
    - type: text
      name: baseName
      label: baseName
    - type: text
      name: mediaType
      label: mediaType
    - type: boolean
      name: isPlainText
      label: isPlainText
- type: field_group
  name: outputs
  label: outputs
  fields:
  - type: list
    name: home
    label: home
  - type: list
    name: page
    label: page
  - type: list
    name: section
    label: section
- type: text
  name: google_verification_meta_field
  label: google_verification_meta_field
