---
label: Config File
hide_body: true
fields:
- name: baseURL
  type: text
  config:
    required: true
  label: Base URL
  description: Hostname (and path) to the root, e.g. http://bugo.io
- name: assetDir
  type: text
  config:
    required: true
  label: Asset Directory
  description: The directory where Hugo finds asset files used in Hugo Pipes.
pages:
- config.yaml
