---
label: Config - Site Styles
hide_body: true
fields:
- type: list
  name: theme_colors
  label: Theme Colors
  description: Add your bootstrap colors here. We've added the basics.
  default:
  - Primary
  - Secondary
  - Gray
  - Gray Dark
- type: textarea
  name: custom_css
  label: Custom CSS
  description: Enter your custom CSS here.
- name: secondary_font
  type: field_group
  config: {}
  fields:
  - name: font_family
    type: text
    config:
      required: false
    label: Font Family
  - name: fonts
    type: include
    config: {}
    template: field-font-family
    label: Fonts
  label: Secondary Font
  description: Add a secondary font. This will be applied to Headers & Block Quotes
- name: primary_font
  type: field_group
  config: {}
  fields:
  - name: font_family
    type: text
    config:
      required: false
    label: Font Family
  - name: fonts
    type: include
    config: {}
    template: field-font-family
    label: Fonts
  label: Primary Font
pages:
- data/styles.yaml
