---
label: Config - Organization
hide_body: true
fields:
- type: text
  name: organization_name
  label: organization_name
- type: text
  name: organization_description
  label: organization_description
- type: field_group
  name: logos
  label: Logos
  fields:
  - type: field_group
    name: header_logo
    label: Header Logo
    fields:
    - type: text
      name: title
      label: title
    - type: file
      name: image
      label: image
    - type: text
      name: caption
      label: caption
    description: Add a header logo to this website.
  - type: field_group
    name: footer_logo
    label: Footer Logo
    fields:
    - type: text
      name: title
      label: title
    - type: file
      name: image
      label: image
    - type: text
      name: caption
      label: caption
    description: Add a footer logo to this website.
  - type: text
    name: seo_logo
    label: seo_logo
    description: This image needs to be a .png file.
- type: field_group
  name: social_accounts
  label: Social Accounts
  fields:
  - type: text
    name: linked_in
    label: linked_in
  - type: text
    name: facebook
    label: facebook
  - type: text
    name: instagram
    label: instagram
  - type: text
    name: twitter
    label: twitter
  - type: text
    name: youtube
    label: youtube
  - type: text
    name: github
    label: github
  - type: text
    name: vimeo
    label: vimeo
  - type: text
    name: pinterest
    label: pinterest
- type: field_group_list
  name: locations
  label: Locations
  fields:
  - type: text
    name: title
    label: Title
  - type: text
    name: address_1
    label: address_1
  - type: text
    name: address_2
    label: address_2
  - type: text
    name: city
    label: city
  - type: text
    name: state
    label: state
  - type: text
    name: zip_code
    label: zip_code
  - type: text
    name: location_name
    label: location_name
  - type: text
    name: email_address
    label: Email Address
  - type: text
    name: phone
    label: Phone
  config:
    labelField: title
pages:
- data/organization.yaml
