---
label: Config - Site Styles
hide_body: true
fields:
- type: list
  name: theme_colors
  label: Theme Colors
  description: Add your bootstrap colors here. We've added the basics.
  default:
  - Primary
  - Secondary
  - Gray
  - Gray Dark
- type: textarea
  name: custom_css
  label: Custom CSS
  description: Enter your custom CSS here.
- name: font_families
  type: field_group_list
  fields:
  - name: font_family
    type: include
    config: {}
    template: field-font-family
    label: Font Family
  config:
    min: 
    max: 
    labelField: 
  label: Font Families
  description: Add Font Families from Google
pages:
- data/styles.yaml
