---
label: Config - Site Styles
hide_body: true
fields:
- type: list
  name: theme_colors
  label: Theme Colors
  description: Add your bootstrap colors here. We've added the basics.
  default:
  - Primary
  - Secondary
  - Gray
  - Gray Dark
- type: textarea
  name: custom_css
  label: Custom CSS
  description: Enter your custom CSS here.
- name: font_families
  type: field_group_list
  fields:
  - name: font_family
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: false
      schema:
        format: markdown
    label: Font Family
    description: Add the font family name
  - name: fonts
    type: include
    config: {}
    template: field-font-family
    label: Fonts
  config:
    min: 
    max: 
    labelField: font_family
  label: Font Families
  description: Add Font Families from Google
pages:
- data/styles.yaml
