---
label: Config - Site Styles
hide_body: true
fields:
- type: list
  name: theme_colors
  label: Theme Colors
  description: Add your bootstrap colors here. We've added the basics.
  default:
  - Primary
  - Secondary
  - Gray
  - Gray Dark
