---
label: Config - Organization
hide_body: true
fields:
- type: field_group
  name: contact_information
  label: contact_information
  fields:
  - type: text
    name: address_1
    label: address_1
  - type: text
    name: address_2
    label: address_2
  - type: text
    name: city
    label: city
  - type: text
    name: state
    label: state
  - type: text
    name: zip_code
    label: zip_code
  - type: text
    name: email_address
    label: email_address
  - type: text
    name: telephone
    label: telephone
  - type: text
    name: mobile
    label: mobile
  - type: text
    name: linked_in
    label: linked_in
  - type: text
    name: facebook
    label: facebook
  - type: text
    name: instagram
    label: instagram
  - type: text
    name: twitter
    label: twitter
  - type: text
    name: youtube
    label: youtube
  - type: text
    name: github
    label: github
  - type: field_group
    name: contact_info
    label: contact_info
    fields:
    - type: text
      name: email_address
      label: email_address
    - type: text
      name: telephone
      label: telephone
    - type: text
      name: mobile
      label: mobile
    - type: list
      name: email_addresses
      label: email_addresses
    - type: list
      name: phones
      label: phones
  - type: field_group
    name: address
    label: address
    fields:
    - type: text
      name: address_1
      label: address_1
    - type: text
      name: address_2
      label: address_2
    - type: text
      name: city
      label: city
    - type: text
      name: state
      label: state
    - type: text
      name: zip_code
      label: zip_code
  - type: field_group
    name: social_accounts
    label: social_accounts
    fields:
    - type: text
      name: linked_in
      label: linked_in
    - type: text
      name: facebook
      label: facebook
    - type: text
      name: instagram
      label: instagram
    - type: text
      name: twitter
      label: twitter
    - type: text
      name: youtube
      label: youtube
    - type: text
      name: github
      label: github
    - type: text
      name: vimeo
      label: vimeo
    - type: text
      name: pinterest
      label: pinterest
  - type: list
    name: locations
    label: locations
  - type: boolean
    name: show_email_labels
    label: show_email_labels
  - type: boolean
    name: show_phone_labels
    label: show_phone_labels
- type: field_group
  name: logos
  label: logos
  fields:
  - type: field_group
    name: header_logo
    label: header_logo
    fields:
    - type: text
      name: title
      label: title
    - type: file
      name: image
      label: image
    - type: text
      name: caption
      label: caption
  - type: field_group
    name: footer_logo
    label: footer_logo
    fields:
    - type: text
      name: title
      label: title
    - type: file
      name: image
      label: image
    - type: text
      name: caption
      label: caption
  - type: text
    name: seo_logo
    label: seo_logo
- type: text
  name: organization_name
  label: organization_name
- type: boolean
  name: show_breadcrumbs
  label: show_breadcrumbs
- type: field_group
  name: contact_info
  label: contact_info
  fields:
  - type: text
    name: email_address
    label: email_address
  - type: text
    name: telephone
    label: telephone
  - type: text
    name: mobile
    label: mobile
  - type: list
    name: email_addresses
    label: email_addresses
  - type: list
    name: phones
    label: phones
- type: field_group
  name: social_accounts
  label: social_accounts
  fields:
  - type: text
    name: linked_in
    label: linked_in
  - type: text
    name: facebook
    label: facebook
  - type: text
    name: instagram
    label: instagram
  - type: text
    name: twitter
    label: twitter
  - type: text
    name: youtube
    label: youtube
  - type: text
    name: github
    label: github
  - type: text
    name: vimeo
    label: vimeo
  - type: text
    name: pinterest
    label: pinterest
- type: field_group_list
  name: locations
  label: locations
  fields:
  - type: text
    name: address_1
    label: address_1
  - type: text
    name: address_2
    label: address_2
  - type: text
    name: city
    label: city
  - type: text
    name: state
    label: state
  - type: text
    name: zip_code
    label: zip_code
  - type: text
    name: location_name
    label: location_name
  - type: field_group_list
    name: email_addresses
    label: email_addresses
    fields:
    - type: text
      name: label
      label: label
    - type: text
      name: email_address
      label: email_address
- type: text
  name: organization_description
  label: organization_description
- type: boolean
  name: show_email_labels
  label: show_email_labels
- type: boolean
  name: show_phone_labels
  label: show_phone_labels
- type: text
  name: cloudinary
  label: cloudinary
- type: field_group
  name: default_featured_image
  label: default_featured_image
  fields:
  - type: text
    name: title
    label: title
  - type: text
    name: image
    label: image
  - type: text
    name: caption
    label: caption
- type: field_group
  name: custom_css
  label: custom_css
  fields:
  - type: text
    name: custom_css
    label: custom_css
- type: list
  name: theme_colors
  label: theme_colors
- type: field_group
  name: media
  label: media
  fields:
  - type: field_group
    name: default_featured_image
    label: default_featured_image
    fields:
    - type: list
      name: excluded_pages
      label: excluded_pages
    - type: text
      name: title
      label: title
    - type: file
      name: image
      label: image
    - type: text
      name: caption
      label: caption
  - type: text
    name: cloudinary_name
    label: cloudinary_name
- type: field_group
  name: styles
  label: styles
  fields:
  - type: list
    name: colors
    label: colors
