---
label: Config - Categories
hide_body: false
is_partial: true
fields:
- type: text
  name: type
  label: Type
  hidden: true
  default: select
  config:
    required: true
- type: text
  name: name
  label: Name
  hidden: true
  config:
    required: true
  default: category
- type: text
  name: label
  label: label
  hidden: true
  default: Category
- type: text
  name: description
  label: Description
  hidden: true
  default: Select a category for this page.
