---
label: Config - Organization
hide_body: true
fields:
- type: text
  name: organization_name
  label: organization_name
- type: text
  name: organization_description
  label: organization_description
- type: field_group
  name: logos
  label: logos
  fields:
  - type: field_group
    name: header_logo
    label: header_logo
    fields:
    - type: text
      name: title
      label: title
    - type: file
      name: image
      label: image
    - type: text
      name: caption
      label: caption
  - type: field_group
    name: footer_logo
    label: footer_logo
    fields:
    - type: text
      name: title
      label: title
    - type: file
      name: image
      label: image
    - type: text
      name: caption
      label: caption
  - type: text
    name: seo_logo
    label: seo_logo
- type: field_group
  name: contact_info
  label: contact_info
  fields:
  - type: text
    name: email_address
    label: email_address
  - type: text
    name: telephone
    label: telephone
  - type: text
    name: mobile
    label: mobile
  - type: list
    name: email_addresses
    label: email_addresses
  - type: list
    name: phones
    label: phones
- type: field_group
  name: social_accounts
  label: social_accounts
  fields:
  - type: text
    name: linked_in
    label: linked_in
  - type: text
    name: facebook
    label: facebook
  - type: text
    name: instagram
    label: instagram
  - type: text
    name: twitter
    label: twitter
  - type: text
    name: youtube
    label: youtube
  - type: text
    name: github
    label: github
  - type: text
    name: vimeo
    label: vimeo
  - type: text
    name: pinterest
    label: pinterest
- type: field_group_list
  name: locations
  label: locations
  fields:
  - type: text
    name: address_1
    label: address_1
  - type: text
    name: address_2
    label: address_2
  - type: text
    name: city
    label: city
  - type: text
    name: state
    label: state
  - type: text
    name: zip_code
    label: zip_code
  - type: text
    name: location_name
    label: location_name
  - type: field_group_list
    name: email_addresses
    label: email_addresses
    fields:
    - type: text
      name: label
      label: label
    - type: text
      name: email_address
      label: email_address
