---
label: Config File
hide_body: true
fields:
- name: baseURL
  type: text
  config:
    required: true
  label: Base URL
  description: Hostname (and path) to the root, e.g. http://bugo.io
- name: blackfriday
  type: field_group
  config: {}
  label: Black Friday
  description: Configure how markdown is rendered
- name: enableemoji
  type: boolean
  label: Enable Emoji
  description: Enable Emoji emoticons support for page content; see the Emoji Cheat
    Sheet. https://www.webpagefx.com/tools/emoji-cheat-sheet/
pages:
- config.yaml
