---
label: Config File
hide_body: true
fields:
- name: assetDir
  type: text
  config:
    required: true
  label: Asset Directory
- name: baseURL
  type: text
  config:
    required: true
pages:
- config.yaml
