---
label: Config - Site Styles
hide_body: true
fields:
- name: global_font
  type: field_group
  config: {}
  fields:
  - name: font_family
    type: text
    config:
      required: false
    label: Font Family
  - name: fonts
    type: include
    config: {}
    template: field-font-family
    label: Fonts
  label: Global Font Family
  description: Add a global font from Google. This font will be used for all elements,
    unless you add a Header font family.
- name: header_font
  type: field_group
  config: {}
  fields:
  - name: font_family
    type: text
    config:
      required: false
    label: Font Family
  - name: fonts
    type: include
    config: {}
    template: field-font-family
    label: Fonts
  label: Header Font Family
  description: Add a header font family from Google. This will be applied to Headers
    & Block Quotes
- type: list
  name: theme_colors
  label: Color Schemes
  description: Add your bootstrap colors here. We've added the basics.
  default:
  - Primary
  - Secondary
  - Gray
  - Gray Dark
- type: textarea
  name: custom_css
  label: Custom CSS
  description: Enter your custom CSS here.
pages:
- data/styles.yaml
